services:
  bd:
    image: mariadb:11.2-jammy
    restart: always
    container_name: bd
    mem_limit: 256m
    mem_reservation: 192m
    cpus: 0.25
    environment:
      MYSQL_DATABASE:             xpenbox_db
      MYSQL_ROOT_PASSWORD:             ${DATASOURCE_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    command: >
      --max-connections=15
      --innodb-buffer-pool-size=64M
      --innodb-log-file-size=8M
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=2
      --innodb-log-buffer-size=2M
      --innodb-page-cleaners=1
      --innodb-read-io-threads=1
      --innodb-write-io-threads=1
      --table-open-cache=32
      --table-definition-cache=32
      --thread-cache-size=4
      --query-cache-size=0
      --query-cache-type=0
      --performance-schema=OFF
      --skip-name-resolve
      --tmp-table-size=4M
      --max-heap-table-size=4M
      --key-buffer-size=4M
      --sort-buffer-size=256K
      --read-buffer-size=128K
      --read-rnd-buffer-size=128K
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: jcabrera9409/xpenbox-back:latest
    platform: linux/amd64
    restart: always
    container_name: backend
    mem_limit: 224m
    mem_reservation: 160m
    cpus: 0.30
    environment:
      DATASOURCE_URL:             ${DATASOURCE_URL}
      DATASOURCE_USERNAME:        ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD:        ${DATASOURCE_PASSWORD}
      CORS_ALLOWED_ORIGINS:       ${CORS_ALLOWED_ORIGINS}
      JWT_PUBLIC_KEY_PATH:        ${JWT_PUBLIC_KEY_PATH}
      JWT_PRIVATE_KEY_PATH:       ${JWT_PRIVATE_KEY_PATH}
      APP_PATH:                   ${APP_PATH}
    depends_on:
      - bd
    volumes:
      - ./ssh/privateKey.pem:/work/keys/privateKey.pem:ro
      - ./ssh/publicKey.pem:/work/keys/publicKey.pem:ro
      - ./logs:/work/logs  

  frontend:
    image: jcabrera9409/xpenbox-front:latest
    platform: linux/amd64
    restart: always
    container_name: frontend
    mem_limit: 128m
    mem_reservation: 96m
    cpus: 0.20
    environment:
      NODE_OPTIONS:   "--max-old-space-size=96"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    mem_limit: 64m
    mem_reservation: 32m
    cpus: 0.10
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro