services:
  backend:
    image: jcabrera9409/xpenbox-back:latest
    platform: linux/amd64
    restart: always
    container_name: backend
    mem_limit: 224m
    mem_reservation: 160m
    cpus: 0.30
    environment:
      DATASOURCE_URL:             ${DATASOURCE_URL}
      DATASOURCE_USERNAME:        ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD:        ${DATASOURCE_PASSWORD}
      CORS_ALLOWED_ORIGINS:       ${CORS_ALLOWED_ORIGINS}
      JWT_PUBLIC_KEY_PATH:        ${JWT_PUBLIC_KEY_PATH}
      JWT_PRIVATE_KEY_PATH:       ${JWT_PRIVATE_KEY_PATH}
      APP_PATH:                   ${APP_PATH}
    depends_on:
      - bd
    volumes:
      - ./ssh/privateKey.pem:/work/keys/privateKey.pem:ro
      - ./ssh/publicKey.pem:/work/keys/publicKey.pem:ro
      - ./logs:/work/logs  

  frontend:
    image: jcabrera9409/xpenbox-front:latest
    platform: linux/amd64
    restart: always
    container_name: frontend
    mem_limit: 128m
    mem_reservation: 96m
    cpus: 0.20
    environment:
      NODE_OPTIONS:   "--max-old-space-size=96"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    mem_limit: 64m
    mem_reservation: 32m
    cpus: 0.10
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro